<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.baomidou</groupId>
        <artifactId>dynamic-datasource-samples</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>spring-boot-4-samples</artifactId>
    <packaging>pom</packaging>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>17</java.version>
        <mybatis-spring-boot-starter.version>4.1.0</mybatis-spring-boot-starter.version>
        <mybatis-plus.version>3.5.17</mybatis-plus.version>
        <p6spy.version>3.9.1</p6spy.version>
        <spring-boot-dependencies.version>4.1.1</spring-boot-dependencies.version>
        <spring-cloud-dependencies.version>2025.1.3</spring-cloud-dependencies.version>
        <springdoc-openapi.version>3.1.1</springdoc-openapi.version>
        <alibaba-nacos-config.version>2025.1.0.0</alibaba-nacos-config.version>
        <beecp.version>3.3.0</beecp.version>
        <commons-dbcp2.version>2.8.0</commons-dbcp2.version>
        <sql-springboot4-starter.version>3.40.0-RELEASE</sql-springboot4-starter.version>
        <seata-spring-boot-starter.version>2.6.0</seata-spring-boot-starter.version>
    </properties>

    <modules>
        <module>add-remove-datasource-sample</module>
        <module>beetlsql-sample</module>
        <module>config-consul-sample</module>
        <module>config-nacos-sample</module>
        <module>druid-sample</module>
        <module>jdbc-template-sample</module>
        <module>load-datasource-from-jdbc-sample</module>
        <module>mybatis-sample</module>
        <module>mybatisplus3-sample</module>
        <module>name-pattern-sample</module>
        <module>quartz-sample</module>
        <module>shardingsphere-jdbc-5.x-core-sample</module>
        <module>spel-sample</module>
        <module>tx-local-sample</module>
        <module>tx-seata-sample</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>dynamic-datasource-spring-boot4-starter</artifactId>
                <version>${ds.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot-dependencies.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud-dependencies.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
                <version>${springdoc-openapi.version}</version>
            </dependency>
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-alibaba-nacos-config</artifactId>
                <version>${alibaba-nacos-config.version}</version>
            </dependency>
            <dependency>
                <groupId>org.mybatis.spring.boot</groupId>
                <artifactId>mybatis-spring-boot-starter</artifactId>
                <version>${mybatis-spring-boot-starter.version}</version>
            </dependency>
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>druid</artifactId>
                <version>${druid.version}</version>
            </dependency>
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>druid-spring-boot-4-starter</artifactId>
                <version>${druid.version}</version>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-spring-boot4-starter</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>
            <dependency>
                <groupId>p6spy</groupId>
                <artifactId>p6spy</artifactId>
                <version>${p6spy.version}</version>
            </dependency>
            <dependency>
                <groupId>com.github.chris2018998</groupId>
                <artifactId>beecp</artifactId>
                <version>${beecp.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-dbcp2</artifactId>
                <version>${commons-dbcp2.version}</version>
            </dependency>
            <dependency>
                <groupId>com.ibeetl</groupId>
                <artifactId>sql-springboot4-starter</artifactId>
                <version>${sql-springboot4-starter.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.seata</groupId>
                <artifactId>seata-spring-boot-starter</artifactId>
                <version>${seata-spring-boot-starter.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
