dataSources:
  # TODO The use of `test_hostname` is related to https://github.com/testcontainers/testcontainers-java/issues/4121
  shardingmaster:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
    jdbcUrl: jdbc:tc:mysql:8.4.7-oraclelinux9://test_hostname/master?TC_INITSCRIPT=db/schema.sql
  shardingslave0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
    jdbcUrl: jdbc:tc:mysql:8.4.7-oraclelinux9://test_hostname/slave1?TC_INITSCRIPT=db/schema.sql
  shardingslave1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
    jdbcUrl: jdbc:tc:mysql:8.4.7-oraclelinux9://test_hostname/slave2?TC_INITSCRIPT=db/schema.sql
rules:
- !SHARDING
  tables:
    t_order:
      actualDataNodes: shardingmaster.t_order$->{0..1}
      tableStrategy:
        standard:
          shardingColumn: order_id
          shardingAlgorithmName: baomidou_inline
      keyGenerateStrategy:
        column: order_id
        keyGeneratorName: baomidou_snowflake
  shardingAlgorithms:
    baomidou_inline:
      type: INLINE
      props:
        algorithm-expression: t_order$->{order_id % 2}
        allow-range-query-with-inline-sharding: true
  keyGenerators:
    baomidou_snowflake:
      type: SNOWFLAKE
- !READWRITE_SPLITTING
  dataSourceGroups:
    baomidou_readwrite_data_sources:
      writeDataSourceName: shardingmaster
      readDataSourceNames:
        - shardingslave0
        - shardingslave1
      loadBalancerName: baomidou_load_balance_algorithm
  loadBalancers:
    baomidou_load_balance_algorithm:
      type: ROUND_ROBIN
- !SINGLE
  tables:
    - "*.*"
props:
  sql-show: true
