spring:
  datasource:
    dynamic:
      datasource:
        master:
          username: sa
          password: ""
          url: jdbc:h2:mem:master;INIT=RUNSCRIPT FROM 'classpath:db/schema.sql'
          driver-class-name: org.h2.Driver
        tenant1_1:
          username: sa
          password: ""
          url: jdbc:h2:mem:tenant1_1;INIT=RUNSCRIPT FROM 'classpath:db/schema.sql'
          driver-class-name: org.h2.Driver
        tenant1_2:
          username: sa
          password: ""
          url: jdbc:h2:mem:tenant1_2;INIT=RUNSCRIPT FROM 'classpath:db/schema.sql'
          driver-class-name: org.h2.Driver
        tenant2_1:
          username: sa
          password: ""
          url: jdbc:h2:mem:tenant2_1;INIT=RUNSCRIPT FROM 'classpath:db/schema.sql'
          driver-class-name: org.h2.Driver
        tenant2_2:
          username: sa
          password: ""
          url: jdbc:h2:mem:tenant2_2;INIT=RUNSCRIPT FROM 'classpath:db/schema.sql'
          driver-class-name: org.h2.Driver
logging:
  level:
    com.baomidou: debug