spring:
  datasource:
    dynamic:
      datasource:
        master:
          username: sa
          password: ""
          url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
          driver-class-name: org.h2.Driver
          init:
            # ddl配置
            schema: classpath:db/schema.sql
            # dml配置
            # data:
        salve:
          username: sa
          password: ""
          url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
          driver-class-name: org.h2.Driver
        teacher:
          username: sa
          password: ""
          url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
          driver-class-name: org.h2.Driver
        student:
          username: sa
          password: ""
          url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
          driver-class-name: org.h2.Driver
logging:
  level:
    com.baomidou: debug